spring:
  application:
    name: MyAI-travel-reimbursement
  datasource:
    url: jdbc:mysql://localhost:3306/travel_db?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&createDatabaseIfNotExist=true
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB

mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.aidemo.myaitravelreimbursement.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

server:
  port: 8080
  servlet:
    context-path: /api/v1

# 文件存储配置
storage:
  base-path: D:/myAI-tool/travel-files
  allowed-extensions: pdf,jpg,jpeg,png,heic,gif,webp

# AI 大模型配置
ai:
  provider: langchain4j
  #okhttp
  #Kimi
#  provider: langchain4j
  base-url: https://api.moonshot.cn/v1
  api-key: sk-FBn2jGPgWM6gkp5xN9fptC7TDkwqXzzzy4pq7v7eOsvAsl8K
  model: kimi-k2.5

  #      智谱
#  base-url: https://open.bigmodel.cn/api/paas/v4/
#  api-key: b6e0db2a29744042a2de425928fb3f69.nzDgy81VBASU7BVV
#  model: glm-5.1
  timeout: 60
  temperature: 1.0
  max-retries: 3

# Knife4j 配置
knife4j:
  enable: true
  production: false
  setting:
    language: zh_cn

# 日志配置
logging:
  level:
    com.aidemo.myaitravelreimbursement: debug
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n"
